kubectl create namespace argo-rollouts

kubectl apply -n argo-rollouts -f https://github.com/argoproj/argo-rollouts/releases/latest/download/install.yaml

curl -LO https://github.com/argoproj/argo-rollouts/releases/latest/download/kubectl-argo-rollouts-linux-amd64

sudo install -o root -g root -m 0755 kubectl-argo-rollouts-linux-amd64 /usr/local/bin/kubectl-argo-rollouts


 canary:
      stableService: {{ template "helm-example.fullname" . }}-stable
      canaryService: {{ template "helm-example.fullname" . }}-canary  

- 참고 깃허브 : https://github.com/jakuboskera/blue-green-canary-argocd-rollouts/blob/main/charts/canary/templates/rollout.yaml


-- Rollout.yaml

apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ template "helm-example.fullname" . }}
  labels:
    app: {{ template "helm-example.name" . }}
    chart: {{ template "helm-example.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 4
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: {{ template "helm-example.name" . }}
      release: {{ .Release.Name }}
  strategy:
     canary:
      maxSurge: "25%"
      maxUnavailable: 0
      steps:
      - setWeight: 25
      - pause: {}
      - setWeight: 100
  template:
    metadata:
      labels:
        app: {{ template "helm-example.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.version }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}